version: 2
formats: all
# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml
# sphinx:
#  configuration: docs/conf.py
python:
    version: 3.6
   install:
      - requirements: requirements/local-docs-build.txt
